In [1]:
from bmondata import Server
server = Server('https://bmon.analysisnorth.com')

In [2]:
df = server.sensor_readings('2CF7F12024901237_power')
df.tail()

                     2CF7F12024901237_power
2022-02-17 02:44:11                     0.2
2022-02-17 02:54:22                     0.0
2022-02-17 03:04:32                     0.0
2022-02-17 03:14:42                     0.3
2022-02-17 03:24:52                     0.2

In [5]:
df['ts'] = df.index.to_pydatetime()
df['diff'] = df.ts.diff()
df.tail(20)

,2CF7F12024901237_power,ts,diff
2022-02-17 02:12:45,0.3,2022-02-17 02:12:45,0 days 00:00:01
2022-02-17 02:12:46,0.1,2022-02-17 02:12:46,0 days 00:00:01
2022-02-17 02:12:47,0.3,2022-02-17 02:12:47,0 days 00:00:01
2022-02-17 02:13:27,0.1,2022-02-17 02:13:27,0 days 00:00:40
2022-02-17 02:13:28,19.2,2022-02-17 02:13:28,0 days 00:00:01
2022-02-17 02:13:29,84.7,2022-02-17 02:13:29,0 days 00:00:01
2022-02-17 02:13:30,84.8,2022-02-17 02:13:30,0 days 00:00:01
2022-02-17 02:13:31,43.3,2022-02-17 02:13:31,0 days 00:00:01
2022-02-17 02:13:37,0.1,2022-02-17 02:13:37,0 days 00:00:06
2022-02-17 02:13:38,0.0,2022-02-17 02:13:38,0 days 00:00:01
2022-02-17 02:13:39,0.0,2022-02-17 02:13:39,0 days 00:00:01
2022-02-17 02:13:40,0.2,2022-02-17 02:13:40,0 days 00:00:01
2022-02-17 02:13:41,0.0,2022-02-17 02:13:41,0 days 00:00:01
2022-02-17 02:23:51,0.2,2022-02-17 02:23:51,0 days 00:10:10
2022-02-17 02:34:01,0.2,2022-02-17 02:34:01,0 days 00:10:10
2022-02-17 02:44:11,0.2,2022-02-17 02:44:11,0 days 00:10:10
2022-02-17 02:54:22,0.0,2022-02-17 02:54:22,0 days 00:10:11
2022-02-17 03:04:32,0.0,2022-02-17 03:04:32,0 days 00:10:10
2022-02-17 03:14:42,0.3,2022-02-17 03:14:42,0 days 00:10:10
2022-02-17 03:24:52,0.2,2022-02-17 03:24:52,0 days 00:10:10